// Authored wardrobe entries. These describe assets, not runtime AI requests.
// Shoes: built-in loafers are 'classic'; catalog shoes fill the 'shoes' slot.
export const BUFFALO_ASPHA_ID = 'buffalo-aspha-mid-olive-v1';
export const BRONZE_TOP_ID = 'desigual-bronze-mesh-v1';
export const LILAC_TOP_ID = 'lilac-portrait-mockneck-v1';
export const CROCHET_TOP_ID = 'desigual-crochet-flowers-v1';
export const PLAID_JUMPER_ID = 'mango-plaid-jumper-v1';
export const STRIPE_JUMPER_ID = 'bershka-asymmetric-stripe-jumper-v1';
export const POINTELLE_FLOWER_ID = 'cream-pointelle-flower-jumper-v1';
export const SILVER_CABLE_ID = 'desigual-silver-cable-jumper-v1';
export const LACROIX_FLOWER_ID = 'desigual-lacroix-flower-sweater-v1';
export const BARREL_JEANS_ID = 'topshop-barrel-jeans-v1';
export const DAVINIA_JEANS_ID = 'desigual-davinia-jeans-v1';
export const LEVIS_94_ID = 'levis-94-wide-leg-v1';
export const TOMMY_MOM_ID = 'tommy-ultra-high-mom-v1';
export const STRADIVARIUS_RELAXED_ID = 'stradivarius-relaxed-v1';
export const MANGO_BLACK_JEANS_ID = 'mango-washed-black-v1';
export const BERSHKA_GREY_ID = 'bershka-grey-wide-leg-v1';
export const TOMMY_CARPENTER_ID = 'tommy-remastered-carpenter-v1';
export const GARMENTS = Object.freeze({
  [BRONZE_TOP_ID]: {
    slot: 'top',
    id: BRONZE_TOP_ID,
    name: 'Bronze Buddha mesh',
    family: 'fitted-long-sleeve-top',
    version: 1,
    status: 'user-liked-after-elbow-correction',
    brandAsProvided: 'Desigual',
    referenceViews: ['front', 'back'],
    details: ['bronze glitter and opaque black horizontal stripes', 'front-facing Buddha on both torso panels', 'neon green outlined sleeve graphics', 'soft white airbrushed patches', 'black bound crew neck', 'long fitted sleeves'],
    material: { construction: 'fine stretch mesh', finish: 'metallic flecks', opaqueBands: 'black' },
    fit: { silhouette: 'close to doll body', sleeve: 'tapered', hem: 'hip', adjustment: 'fixed authored fit for first review' },
    exclusions: ['striped-shirt', 'knit-sweater'],
    layering: { coversWaistband: true },
    uncertainties: ['exact sleeve characters are not transcribed', 'generated artwork is interpretive', 'same front-facing motif is reused on back', 'side seam alignment and physical transparency need visual review'],
    authoring: { texture: 'bronze-atlas.js', runtimeGeneration: false, sourcePhotosBundled: false },
  },
  [LILAC_TOP_ID]: {
    slot: 'top',
    id: LILAC_TOP_ID, name: 'Lilac portrait mock neck', family: 'fitted-long-sleeve-top', version: 1,
    status: 'reference-study-awaiting-visual-review', brandAsProvided: null,
    referenceViews: ['front','back'],
    details: ['mauve portrait and flowers on front', 'plain pale silvery-lilac back', 'navy sleeves with alternating circle and dot bands', 'short raised ribbed neck', 'long sleeves with wrist gathering', 'longer close-fitting torso'],
    material: { construction: 'textured fabric; exact fibre unconfirmed', finish: 'subtle metallic back sheen' },
    fit: { silhouette: 'close to doll body', sleeve: 'tapered with cuff gathers', hem: 'lower hip', adjustment: 'fixed authored fit for review' },
    exclusions: ['striped-shirt','knit-sweater'],
    layering: { coversWaistband: true },
    uncertainties: ['portrait and floral artwork are interpretive', 'physical material and brand are not established from pictures', 'exact seam placement and print scale need visual review'],
    authoring: { texture: 'lilac-atlas.js', runtimeGeneration: false, sourcePhotosBundled: false },
  },
  [CROCHET_TOP_ID]: {
    slot: 'top',
    id: CROCHET_TOP_ID, name: 'Blue crochet flowers', family: 'cropped-crochet-sweater', version: 1,
    status: 'reference-study-awaiting-visual-review', brandAsProvided: 'Desigual',
    source: { page: 'https://www.desigual.com/it_IT/26SWJFXG.html', sku: '26SWJFXG5050', fetchedForAuthoring: '2026-10-08' },
    referenceViews: ['front on model', 'back three-quarter on model', 'front flat lay', 'street action'],
    details: ['joined hexagonal flower motifs: navy petals with spoked turquoise centres, pale-blue petals, cream petals with navy centres, small navy wheels', 'open cream lace between motifs', 'wide filet-crochet neckband on a broad scoop neck', 'cropped boxy body', 'long slightly flared sleeves reaching the knuckles', 'scalloped hem and cuffs'],
    material: { construction: 'joined crochet motifs with openwork filler', composition: '60% cotton, 40% acrylic per composition section; the same page also says 100% cotton', finish: 'matte yarn' },
    fit: { silhouette: 'boxy, cropped at the waist', sleeve: 'slightly flared, covers half the mitten', hem: 'scalloped at waist', adjustment: 'fixed authored fit for review' },
    exclusions: ['striped-shirt','knit-sweater'],
    uncertainties: ['motif layout is a procedural repeat, not a stitch-for-stitch copy', 'upper back and back neckline are hidden by hair in the back photo', 'dropped shoulders and the ladder seams at shoulder and sleeve are not modelled', 'scallops do not follow individual motif edges'],
    authoring: { texture: 'procedural crochetData() in src/doll/model.js, drawn locally when first worn', runtimeGeneration: false, sourcePhotosBundled: false },
  },
  [PLAID_JUMPER_ID]: {
    slot: 'top',
    id: PLAID_JUMPER_ID, name: 'Brushed windowpane jumper', family: 'oversized-knit-jumper', version: 1,
    status: 'reference-study-awaiting-visual-review', brandAsProvided: 'Mango',
    source: { page: 'https://www.zalando.ie/mango-jumper-light-blue-zir03dt4f-001.html', note: 'page blocked automated fetching; user supplied phone screenshots of 7 product photos' },
    referenceViews: ['front on model', 'front full length', 'knit close-up', 'back on model', 'sleeve and hem close-up', 'front flat lay', 'crouching side'],
    details: ['large windowpane check knitted in (jacquard), not printed', 'wide bands of diagonal hatching in rust-brown and grey-taupe', 'thin pale-blue lines through bands and cream windows', 'brushed fuzzy cream ground', 'ribbed crew neck', 'deep ribbed hem band', 'ribbed cuffs gathering full sleeves', 'oversized boxy body with dropped shoulders'],
    material: { construction: 'heavy brushed jacquard knit', composition: 'not visible in the supplied screenshots', finish: 'soft halo' },
    fit: { silhouette: 'oversized, boxy', sleeve: 'full, gathered into ribbed cuffs', hem: 'hip, deep rib band', adjustment: 'fixed authored fit for review' },
    wear: { userNote: 'rarely worn: oversized and very warm for the local climate' },
    exclusions: ['striped-shirt','knit-sweater'],
    layering: { coversWaistband: true },
    uncertainties: ['check scale and band order are an interpretation of the photos', 'fibre composition is unknown', 'the shirt collar and cuffs in the photos are styling, not part of the jumper'],
    authoring: { texture: 'procedural plaidData() in src/doll/model.js, drawn locally when first worn', runtimeGeneration: false, sourcePhotosBundled: false },
  },
  [STRIPE_JUMPER_ID]: {
    slot: 'top',
    id: STRIPE_JUMPER_ID, name: 'Asymmetric rustic stripe jumper', family: 'off-shoulder-knit-jumper', version: 1,
    status: 'reference-study-awaiting-visual-review', brandAsProvided: 'Bershka',
    source: { note: 'user supplied two phone screenshots of a Myntra listing (Bershka Asymmetric Rustic Stripe Jumper): front on model and a flat lay; no other views were available' },
    referenceViews: ['front on model', 'front flat lay'],
    details: ['wide asymmetric neckline worn off one shoulder: high at the base of the neck on her right, slipping below the shoulder onto the upper arm on her left', 'ecru slub ("rustic") knit with even dark green horizontal stripes', 'stripes near the neckline follow its slant and level out lower down', 'deep plain ecru ribbed hem band', 'long straight sleeves with deep plain ribbed cuffs', 'boxy body with dropped shoulders, ending at the high hip', 'narrow plain edge around the neckline'],
    material: { construction: 'medium-weight slub knit', composition: 'not visible in the supplied screenshots', finish: 'matte, flecked yarn' },
    fit: { silhouette: 'relaxed, boxy', sleeve: 'long and straight into deep ribbed cuffs', hem: 'high hip, deep rib band', neckline: 'off her left shoulder', adjustment: 'fixed authored fit for review' },
    exclusions: ['striped-shirt','knit-sweater'],
    // The bare shoulder is deliberate: her left arm shows above the neckline, and the body (not the sleeve) covers it just
    // below. Sleeve-local height above which the sleeve alone does not cover that arm.
    layering: { coversWaistband: true, bareShoulder: { side: 1, above: -.23 } },
    uncertainties: ['the back was not shown; its neckline and stripes are inferred', 'the flat lay and the worn photo disagree on which side sits lower; the worn photo is followed', 'stripe count is adapted to her short torso', 'the bare shoulder is a skin-coloured piece inside the jumper, because her body under clothes is cream felt'],
    authoring: { texture: 'procedural stripeKnitData() in src/doll/model.js, drawn locally when first worn', runtimeGeneration: false, sourcePhotosBundled: false },
  },
  [POINTELLE_FLOWER_ID]: {
    slot: 'top',
    id: POINTELLE_FLOWER_ID, name: 'Cream pointelle flower jumper', family: 'boxy-openwork-knit-jumper', version: 1,
    status: 'reference-study-awaiting-visual-review', brandAsProvided: null,
    source: { note: "the user's own jumper, photographed flat on the floor from the front and the back; the user could not find the product online" },
    referenceViews: ['front flat on the floor', 'back flat on the floor'],
    details: ['cream openwork knit: bands of two staggered eyelet rows between raised horizontal ridges', 'eight raised embroidered flowers scattered over the front only: six raspberry petals with a darker centre, two dark green leaves above each, so the flowers hang', 'wide boat neckline', 'raglan seams from the neckline to the underarms', 'boxy body about as long as it is wide, ending at the hip', 'long wide straight sleeves', 'narrow plain bands with small scallops at the neckline, hem and sleeve ends'],
    material: { construction: 'fine openwork (pointelle) knit', composition: 'not known', finish: 'matte cotton-like yarn' },
    fit: { silhouette: 'boxy, relaxed', sleeve: 'long, wide and straight', hem: 'hip, narrow scalloped band', neckline: 'wide boat neck', adjustment: 'fixed authored fit for review' },
    exclusions: ['striped-shirt','knit-sweater'],
    layering: { coversWaistband: true },
    uncertainties: ['eyelet spacing is coarser than the real knit so it reads at the doll\'s size', 'flower placement is measured from the front photo and adapted to her short torso', 'the front photo has a cool colour cast; colours aim between the two photos', 'her body under clothes is cream felt, so skin is drawn inside the jumper to show through the eyelets'],
    authoring: { texture: 'procedural pointelleData() in src/doll/model.js; flowers are small raised shapes', runtimeGeneration: false, sourcePhotosBundled: false },
  },
  [SILVER_CABLE_ID]: {
    slot: 'top',
    id: SILVER_CABLE_ID, name: 'Silver foil cable jumper', family: 'cropped-cable-knit-jumper', version: 1,
    status: 'reference-study-awaiting-visual-review', brandAsProvided: 'Desigual',
    source: { note: 'user supplied five phone screenshots of a Modivo listing (Desigual knit jumper): front and back on a model, a front close-up, a neckline close-up and a flat lay' },
    referenceViews: ['front on model', 'back on model', 'front close-up', 'neckline close-up', 'front flat lay'],
    details: ['black yarn coated with silver foil: raised stitches shine silver, grooves and gaps stay black', 'centre panel of fine twisted-stitch cables forming a diamond lattice, front and back', 'columns of twisted ribs and small rope cables either side of the panel', 'a large wavy cable down each sleeve, with black slits where its strands part', 'deep ribbed hem band, long ribbed cuffs and a ribbed crew neck, black in every groove', 'slim fit, cropped at the waist, set-in sleeves'],
    material: { construction: 'cable knit', composition: 'not visible in the supplied screenshots', finish: 'metallic silver foil over black' },
    fit: { silhouette: 'slim', sleeve: 'long and fitted, gathered into long ribbed cuffs', hem: 'cropped at the waist, deep rib band', adjustment: 'fixed authored fit for review' },
    exclusions: ['striped-shirt','knit-sweater'],
    uncertainties: ['the lattice and cables are drawn procedurally, not stitch for stitch', 'the exact order of the narrow columns beside the panel is simplified', 'silver is shaded with the studio lights only; there is no reflected environment'],
    authoring: { texture: 'procedural silverKnitData() in src/doll/model.js, drawn locally when first worn', runtimeGeneration: false, sourcePhotosBundled: false },
  },
  [LACROIX_FLOWER_ID]: {
    slot: 'top',
    id: LACROIX_FLOWER_ID, name: 'Lacroix giant flower sweater', family: 'printed-knit-sweater', version: 1,
    status: 'reference-study-awaiting-visual-review', brandAsProvided: 'Desigual, designed by Christian Lacroix',
    source: { note: 'user supplied five phone screenshots of the desigual.com (NZ) listing "Sweater designed by Mr. Christian Lacroix": flat lay, front and back on a model, a neckline close-up and a front close-up' },
    referenceViews: ['front flat lay', 'front on model', 'back on model', 'neckline close-up', 'front close-up'],
    details: ['fuzzy olive-green knit', 'one giant painterly violet flower across the front: five streaked petals fading to lilac and white, a mint throat, black stamens and a thick black stem from her right shoulder', 'a second violet flower low on her right with a diagonal black stem, and a white and mint peony sketched in black low on her left', 'a giant violet flower across the upper back', 'flowers on both forearms: violet on her right, the peony and violet on her left', 'olive ribbed cuffs, a lilac ribbed crew neck, and a hem rib that carries the print', 'regular fit to the high hip'],
    material: { construction: 'brushed (fuzzy) knit with a knitted-in print', composition: 'not visible in the supplied screenshots', finish: 'soft halo' },
    fit: { silhouette: 'regular, close but not tight', sleeve: 'long, slightly loose, ribbed cuffs', hem: 'high hip', adjustment: 'fixed authored fit for review' },
    exclusions: ['striped-shirt','knit-sweater'],
    layering: { coversWaistband: true },
    uncertainties: ['the flowers are painted procedurally from the photos, not copied; their shapes and streaks are an interpretation', 'flower sizes are adapted to her short, wide torso', 'the back is read from one model photo partly hidden by hair'],
    authoring: { texture: 'procedural lacroixData() in src/doll/model.js, painted locally when first worn', runtimeGeneration: false, sourcePhotosBundled: false },
  },
  [BARREL_JEANS_ID]: {
    slot: 'bottom',
    id: BARREL_JEANS_ID, name: 'Acid-wash barrel jeans', family: 'barrel-leg-jeans', version: 1,
    status: 'user-approved-after-revisions', brandAsProvided: 'Topshop',
    source: { note: 'user supplied four phone screenshots of the product gallery (front on model, back detail, back full length, flat lay)' },
    referenceViews: ['front on model', 'back pocket close-up', 'back full length', 'front flat lay'],
    details: ['low rise', 'very wide barrel (horseshoe) legs, widest around the knee, full length resting on the shoes', 'side seams twisting forward toward the hem', 'horizontal darts across each knee', 'slanted front pockets', 'belt loops, silver shank button and zip fly', 'tan contrast topstitching', 'back yoke and patch pockets with pointed buttoned flaps', 'welt slit above the right back pocket', 'brown suede waistband patch', 'mid-dark blue marbled acid wash with a grey cast'],
    material: { construction: 'rigid denim', composition: 'not visible in the supplied screenshots', finish: 'marbled acid wash' },
    fit: { silhouette: 'barrel', rise: 'low', length: 'full, resting on the shoes', adjustment: 'fixed authored fit for review' },
    uncertainties: ['folds are procedural', 'exact pocket and dart placement adapted to the doll', 'brand text on the patch is not reproduced'],
    authoring: { texture: 'topshop-denim.js: flat-lit seamless swatch processed from the product flat lay (at the user\'s request)', runtimeGeneration: false, sourcePhotosBundled: 'fabric swatch only' },
    // Construction for makeJeans() in src/doll/model.js. Rows are [y, rx, rz] (hips) and [y, rx, rz, cx] (legs).
    build: {
      template: 'jeans', legName: 'barrel-leg',
      // Hips flow into the legs at the crotch; hips and legs are mapped by distance along the fabric at the same denim
      // scale as before (about 3.7 repeats per unit around, 1.03 per unit down), so their tiles are 1.
      crotch: { top: 1.2, y: .95 }, uvScale: [3.7, 1.03],
      tiles: { small: [2.45, .66], legs: [1, 1], hips: [1, 1] },
      hips: [[1.22, .255, .172], [1.13, .276, .193], [1.04, .292, .198], [.97, .3, .186], [.935, .25, .11]],
      legs: [[1.03, .145, .185, .13], [.95, .158, .185, .158], [.75, .168, .188, .172], [.55, .172, .188, .176], [.35, .17, .186, .174], [.18, .167, .184, .17], [.06, .166, .183, .168]],
      hem: 'rests-on-shoe', folds: { base: .005, low: .011, stack: .011 }, twist: Math.PI / 4, kneeSeams: .64,
      gradient: [.86, .22], whiskers: .12,
      waistband: { y: 1.195, rx: .258, rz: .175, h: .05 },
      loops: [-2.7, -1.45, -.55, .55, 1.45, 2.7, Math.PI],
      button: { colour: '#c9ccd0' }, thread: '#8f744f',
      fly: [[.034, 1.168], [.036, 1.08], [.02, 1.045], [0, 1.035]],
      frontPocket: { type: 'slant', line: [[.165, 1.168], [.218, 1.11], [.265, 1.065]] },
      sideSeamTop: [[.278, 1.12], [.29, 1.04]], seamEnd: .1,
      backYoke: [[.272, 1.165], [.14, 1.148], [.004, 1.13]],
      backPocket: { x: .122, outline: [[-.076, 1.11], [.076, 1.11], [.073, .99], [0, .958], [-.073, .99]], stitchBelow: 1.05,
        flap: [[-.082, 1.128], [.082, 1.128], [.08, 1.084], [0, 1.062], [-.08, 1.084]],
        flapStitch: [[-.074, 1.12], [.074, 1.12], [.072, 1.088], [0, 1.07], [-.072, 1.088], [-.074, 1.12]], button: 1.076 },
      centreBack: [[.004, 1.13], [.004, 1.05], [0, .99]],
      welt: [[-.19, 1.14], [-.07, 1.137]],
      labelPatch: { name: 'suede-patch', size: [.088, .05, .005], colour: '#a87348', position: [.07, 1.2, -(.177 + .004)], rotationY: Math.PI - .27 },
    },
  },
  [DAVINIA_JEANS_ID]: {
    slot: 'bottom',
    id: DAVINIA_JEANS_ID, name: 'Davinia heart jeans', family: 'high-rise-straight-cropped-jeans', version: 1,
    status: 'reference-study-awaiting-visual-review', brandAsProvided: 'Desigual',
    source: { note: 'user supplied four phone screenshots of a Ceneo listing (Desigual Jeansy Davinia 22SWDD01): front on model, waist close-up, flat lay, back on model' },
    referenceViews: ['front on model', 'waist and pocket close-up', 'front flat lay', 'back on model'],
    details: ['high rise', 'slim straight legs cropped at the ankle with a raw frayed hem', 'light blue acid wash, paler on the thighs', 'raw frayed top edge on the waistband', 'copper shank button and orange contrast stitching', 'scoop front pockets', 'coin pocket with a small red embroidered heart', 'small light abrasions near the pocket and on the thigh', 'plain back patch pockets, V yoke and a brown leather patch'],
    material: { construction: 'rigid denim', composition: 'not visible in the supplied screenshots', finish: 'acid wash' },
    fit: { silhouette: 'straight, slim', rise: 'high', length: 'cropped at the ankle', adjustment: 'fixed authored fit for review' },
    uncertainties: ['folds are procedural', 'pocket and abrasion placement adapted to the doll', 'leather patch lettering is not reproduced'],
    authoring: { texture: 'desigual-davinia-denim.js: flat-lit seamless swatch processed from the product flat lay', runtimeGeneration: false, sourcePhotosBundled: 'fabric swatch only' },
    build: {
      template: 'jeans', legName: 'jeans-leg', fallback: [110, 123, 146], frayColour: '#d8dfe6',
      // Hips and legs are mapped by distance along the fabric (uvScale, repeats per unit), so their tiles are 1.
      tiles: { small: [2.8, .38], legs: [1, 1], hips: [1, 1] },
      // Slim straight legs, taken in as far as the doll's legs allow; the hips blend into them at the crotch.
      hips: [[1.3, .262, .168], [1.2, .27, .184], [1.1, .28, .19], [1.02, .276, .178], [.97, .262, .162], [.935, .2, .085]],
      legs: [[1.12, .13, .165, .128], [1.03, .132, .162, .128], [.95, .128, .155, .136], [.8, .118, .14, .148], [.6, .106, .124, .155], [.45, .101, .116, .157], [.34, .1, .112, .158]],
      crotch: { top: 1.1, y: .95 }, uvScale: [4, .66],
      hem: 'raw-crop', folds: { base: .002, low: .003 }, gradient: [.92, .12], whiskers: .1, thighFade: .1,
      waistband: { y: 1.275, rx: .264, rz: .17, h: .05, frayed: true },
      loops: [-2.6, -1.5, -.62, .62, 1.5, 2.6, Math.PI],
      button: { colour: '#a8743a' }, thread: '#b5783f',
      fly: [[.036, 1.25], [.038, 1.13], [.022, 1.085], [0, 1.075]],
      frontPocket: { type: 'scoop', line: [[.15, 1.25], [.165, 1.2], [.2, 1.172], [.258, 1.16]] },
      coinPocket: { outline: [[-.235, 1.245], [-.185, 1.245], [-.19, 1.19], [-.232, 1.19], [-.235, 1.245]], heart: [-.21, 1.218] },
      abrasions: [[-.19, 1.13, .026], [-.205, 1.112, .018], [.13, .99, .022], [-.11, .87, .016]],
      sideSeamTop: [[.266, 1.25], [.282, 1.12], [.284, 1.04]], seamEnd: .345,
      backYoke: [[.268, 1.21], [.14, 1.19], [.004, 1.165]],
      backPocket: { x: .12, outline: [[-.072, 1.15], [.072, 1.15], [.07, 1.03], [0, 1.0], [-.07, 1.03]], stitchBelow: 1.1 },
      centreBack: [[.004, 1.165], [.004, 1.07], [0, 1.0]],
      labelPatch: { name: 'leather-patch', size: [.07, .04, .005], colour: '#9b6a42', position: [-.07, 1.275, -(.17 + .004)], rotationY: Math.PI + .27 },
    },
  },
  [LEVIS_94_ID]: {
    slot: 'bottom',
    id: LEVIS_94_ID, name: "Levi's '94 baggy wide leg", family: 'wide-leg-jeans', version: 1,
    status: 'reference-study-awaiting-visual-review', brandAsProvided: "Levi's",
    source: { note: "user supplied six product images (\"Levi's 94 Wide Leg\"; label reads The Baggy Wide Leg): back pocket close-up, front flat lay, front, back and side on model, full-length front" },
    referenceViews: ['back pocket close-up', 'front flat lay', 'front on model', 'back on model', 'side on model', 'full-length front'],
    details: ['low-to-mid rise', 'wide legs falling straight and widening slightly to the hem, full length pooling over the shoes', 'washed black faded to charcoal, faint whiskers across the upper thighs, visible twill', 'raw frayed edges on the front pocket openings', 'coin pocket, belt loops, dark metal button', 'back yoke, five-pocket back pockets with tonal double-arc stitching and frayed nicks on their tops', 'red tab on the wearer\'s right back pocket', 'tan printed patch on the back waistband'],
    material: { construction: 'rigid denim', composition: 'not visible in the supplied images', finish: 'washed black' },
    fit: { silhouette: 'wide leg', rise: 'low to mid', length: 'full, resting on the shoes (confirmed by the user)', adjustment: 'fixed authored fit for review' },
    uncertainties: ['folds are procedural', 'photos disagree on brightness (studio lighting); colour aims between the flat lay and the model shots', 'patch and tab carry no lettering or logo'],
    authoring: { texture: 'levis-94-denim.js: flat-lit seamless swatch processed from the product flat lay', runtimeGeneration: false, sourcePhotosBundled: 'fabric swatch only' },
    build: {
      template: 'jeans', legName: 'jeans-leg', fallback: [36, 36, 41], frayColour: '#5d595c',
      crotch: { top: 1.18, y: .95 }, uvScale: [3.7, 1.03],
      tiles: { small: [2.45, .66], legs: [1, 1], hips: [1, 1] },
      hips: [[1.235, .256, .172], [1.14, .276, .193], [1.04, .294, .198], [.97, .306, .19], [.935, .25, .11]],
      // Wide legs: straight from the hip and widening gently to the hem, full length, resting on the shoes (the user
      // confirmed this length is right on them).
      legs: [[1.03, .148, .18, .13], [.95, .155, .18, .152], [.75, .163, .183, .168], [.55, .171, .186, .176], [.35, .179, .19, .184], [.18, .186, .194, .19], [.06, .19, .197, .194]],
      hem: 'rests-on-shoe', folds: { base: .005, low: .011, stack: .008 },
      gradient: [.86, .22], whiskers: .15, thighFade: .1,
      waistband: { y: 1.21, rx: .258, rz: .175, h: .05 },
      loops: [-2.7, -1.45, -.55, .55, 1.45, 2.7, Math.PI],
      button: { colour: '#4c4b4e' }, thread: '#4a4648',
      fly: [[.034, 1.183], [.036, 1.09], [.02, 1.05], [0, 1.04]],
      frontPocket: { type: 'slant', line: [[.15, 1.184], [.205, 1.178], [.245, 1.158], [.27, 1.115]], fray: true },
      coinPocket: { outline: [[-.225, 1.183], [-.18, 1.181], [-.184, 1.135], [-.222, 1.137], [-.225, 1.183]] },
      seamEnd: .1,
      backYoke: [[.268, 1.182], [.14, 1.162], [.004, 1.142]],
      backPocket: { x: .12, outline: [[-.07, 1.128], [.07, 1.128], [.066, 1.005], [0, .978], [-.066, 1.005]], stitchBelow: 1.07,
        arcuate: [.052, 1.085, .03], arcuateColour: '#161416', nicks: [-.035, .02],
        tab: { side: -1, inset: .066, y: 1.09, colour: '#c3262f' } },
      centreBack: [[.004, 1.142], [.004, 1.05], [0, .985]],
      labelPatch: { name: 'printed-patch', size: [.085, .052, .005], colour: '#c49a6c', printColour: '#9c4a3c', position: [-.07, 1.21, -(.175 + .004)], rotationY: Math.PI + .27 },
    },
  },
  [TOMMY_MOM_ID]: {
    slot: 'bottom',
    id: TOMMY_MOM_ID, name: 'Tommy ultra high rise mom jeans', family: 'mom-jeans', version: 1,
    status: 'reference-study-awaiting-visual-review', brandAsProvided: 'Tommy Jeans',
    source: { note: 'user supplied four phone screenshots of an ASOS listing (Tommy Jeans ultra high rise mom jean in mid wash): front and back on model, back pocket close-up, front waist close-up' },
    referenceViews: ['front on model', 'back on model', 'back pocket close-up', 'front waist close-up'],
    details: ['ultra high rise at the natural waist', 'mom fit: roomy hips and thighs tapering to a narrow ankle-length hem', 'even mid indigo wash, slightly paler on the thighs', 'tan-orange topstitching, scoop front pockets with copper rivets, silver button', 'coin pocket with a tiny flag badge', 'back yoke, patch pockets crossed by a double stitched bar, a small flag badge on the wearer\'s right pocket', 'red, white and navy flag patch on the back waistband'],
    material: { construction: 'rigid denim', composition: 'not visible in the supplied screenshots', finish: 'mid wash' },
    fit: { silhouette: 'mom, tapered', rise: 'ultra high', length: 'ankle', adjustment: 'fixed authored fit for review' },
    uncertainties: ['folds are procedural', 'badges and patch are colour blocks without lettering'],
    authoring: { texture: 'tommy-mom-denim.js: flat-lit seamless swatch processed from the front close-up', runtimeGeneration: false, sourcePhotosBundled: 'fabric swatch only' },
    build: {
      template: 'jeans', legName: 'jeans-leg', fallback: [30, 46, 76],
      // The swatch comes from a zoomed close-up, so it repeats more often than the other pairs' to keep the grain fine.
      crotch: { top: 1.12, y: .95 }, uvScale: [6, 3],
      tiles: { small: [5.5, 2.8], legs: [1, 1], hips: [1, 1] },
      // Ultra high rise: the waistband sits at her natural waist.
      hips: [[1.36, .268, .168], [1.27, .274, .18], [1.15, .288, .196], [1.05, .296, .2], [.97, .292, .19], [.935, .24, .1]],
      // Mom fit: roomy through the thigh, tapering to a narrow hem at the ankle, above her shoes.
      legs: [[1.03, .152, .18, .14], [.95, .154, .178, .152], [.8, .152, .172, .158], [.6, .138, .158, .16], [.42, .127, .148, .16], [.24, .125, .145, .16]],
      hem: 'ankle', folds: { base: .004, low: .007 }, gradient: [.88, .18], whiskers: .14, thighFade: .1,
      waistband: { y: 1.335, rx: .267, rz: .169, h: .05 },
      loops: [-2.6, -1.5, -.62, .62, 1.5, 2.6, Math.PI],
      button: { colour: '#c9ccd0' }, thread: '#c27a3a',
      fly: [[.036, 1.31], [.038, 1.16], [.022, 1.1], [0, 1.09]],
      frontPocket: { type: 'scoop', line: [[.15, 1.31], [.165, 1.255], [.2, 1.225], [.262, 1.21]] },
      coinPocket: { outline: [[-.236, 1.305], [-.19, 1.305], [-.194, 1.25], [-.233, 1.25], [-.236, 1.305]], badge: [-.214, 1.27] },
      rivets: [[.152, 1.305], [.262, 1.215]],
      seamEnd: .245,
      backYoke: [[.27, 1.27], [.14, 1.235], [.004, 1.205]],
      backPocket: { x: .122, outline: [[-.08, 1.2], [.08, 1.2], [.076, 1.055], [0, 1.025], [-.076, 1.055]], stitchBelow: 1.15,
        bars: [1.132, 1.117], badge: { side: -1, out: .032, y: 1.1245 } },
      centreBack: [[.004, 1.205], [.004, 1.1], [0, 1.0]],
      labelPatch: { name: 'flag-patch', size: [.08, .05, .005], colour: '#1c2747', position: [-.08, 1.338, -(.169 + .004)], rotationY: Math.PI + .3,
        blocks: [[-.038, .002, 0, .023, '#f2f2f0'], [0, .002, .038, .023, '#c8202f']] },
    },
  },
  [STRADIVARIUS_RELAXED_ID]: {
    slot: 'bottom',
    id: STRADIVARIUS_RELAXED_ID, name: 'Stradivarius relaxed jeans', family: 'relaxed-wide-jeans', version: 1,
    status: 'reference-study-awaiting-visual-review', brandAsProvided: 'Stradivarius',
    source: { note: 'user supplied four phone screenshots of a Zalando listing (Stradivarius, Relaxed, Petite): front close-up, front and back on model, side close-up' },
    referenceViews: ['front close-up', 'front on model', 'back on model', 'side close-up'],
    details: ['low to mid rise', 'relaxed wide straight legs, full length, pooling on the floor', 'very light bleached blue wash with soft whiskers at the hips', 'classic five-pocket front: scoop pockets, coin pocket, copper rivets and button', 'pale tonal stitching', 'plain back patch pockets', 'small beige patch on the back waistband'],
    material: { construction: 'rigid denim', composition: 'not visible in the supplied screenshots', finish: 'bleached light wash' },
    fit: { silhouette: 'relaxed wide', rise: 'low to mid', length: 'full, pooling over the shoes', adjustment: 'fixed authored fit for review' },
    uncertainties: ['folds are procedural', 'patch lettering not reproduced'],
    authoring: { texture: 'stradivarius-denim.js: flat-lit seamless swatch processed from the front close-up', runtimeGeneration: false, sourcePhotosBundled: 'fabric swatch only' },
    build: {
      template: 'jeans', legName: 'jeans-leg', fallback: [154, 171, 192],
      crotch: { top: 1.18, y: .95 }, uvScale: [3.7, 1.03],
      tiles: { small: [2.45, .66], legs: [1, 1], hips: [1, 1] },
      hips: [[1.235, .256, .172], [1.14, .276, .193], [1.04, .294, .198], [.97, .306, .19], [.935, .25, .11]],
      // Relaxed wide straight legs, full length: the hem rests on the shoes and stacks a little.
      legs: [[1.03, .148, .18, .13], [.95, .155, .18, .152], [.75, .162, .183, .166], [.55, .168, .186, .172], [.35, .174, .189, .178], [.18, .18, .193, .184], [.06, .184, .196, .188]],
      hem: 'rests-on-shoe', folds: { base: .005, low: .012, stack: .01 },
      gradient: [.9, .14], whiskers: .12, thighFade: .06,
      waistband: { y: 1.21, rx: .258, rz: .175, h: .05 },
      loops: [-2.7, -1.45, -.55, .55, 1.45, 2.7, Math.PI],
      button: { colour: '#b57a55' }, thread: '#9eaab6',
      fly: [[.034, 1.183], [.036, 1.09], [.02, 1.05], [0, 1.04]],
      frontPocket: { type: 'scoop', line: [[.15, 1.184], [.165, 1.14], [.2, 1.112], [.262, 1.1]] },
      coinPocket: { outline: [[-.236, 1.18], [-.19, 1.18], [-.194, 1.128], [-.233, 1.128], [-.236, 1.18]] },
      rivets: [[.152, 1.18], [.262, 1.105]],
      seamEnd: .1,
      backYoke: [[.268, 1.182], [.14, 1.162], [.004, 1.142]],
      backPocket: { x: .122, outline: [[-.074, 1.128], [.074, 1.128], [.07, 1.0], [0, .972], [-.07, 1.0]], stitchBelow: 1.07 },
      centreBack: [[.004, 1.142], [.004, 1.05], [0, .985]],
      labelPatch: { name: 'paper-patch', size: [.06, .032, .004], colour: '#d9c8a6', position: [-.065, 1.21, -(.175 + .004)], rotationY: Math.PI + .25 },
    },
  },
  [MANGO_BLACK_JEANS_ID]: {
    slot: 'bottom',
    id: MANGO_BLACK_JEANS_ID, name: 'Mango washed black jeans', family: 'relaxed-straight-jeans', version: 1,
    status: 'reference-study-awaiting-visual-review', brandAsProvided: 'Mango (MNG Denim)',
    source: { note: 'user supplied five eBay listing photos (the pair is old): back flat lay on a wooden floor (twice), front waist close-ups and a front flat lay on grey carpet' },
    referenceViews: ['back flat lay', 'front waist close-up', 'front pocket close-up', 'front flat lay'],
    details: ['high rise', 'relaxed straight legs tapering slightly to an ankle-length hem', 'charcoal washed black with a mottled stone-wash, paler on thighs and seams', 'five-pocket front with copper rivets and a silver button', 'plain back patch pockets with a short dart above each instead of a yoke', 'black leather patch on the back waistband', 'light grey double topstitching on the seams, pockets, fly, waistband and hem, with paler bleached seams'],
    material: { construction: 'rigid denim', composition: 'not visible in the supplied photos', finish: 'stone-washed black' },
    fit: { silhouette: 'relaxed straight, slight taper', rise: 'high', length: 'ankle', adjustment: 'fixed authored fit for review' },
    uncertainties: ['folds are procedural', 'photos are flash-lit or warm-lit listing photos; colour aims between them', 'patch carries no lettering'],
    authoring: { texture: 'mango-denim.js: flat-lit seamless swatch processed from the front flat lay', runtimeGeneration: false, sourcePhotosBundled: 'fabric swatch only' },
    build: {
      template: 'jeans', legName: 'jeans-leg', fallback: [53, 56, 58],
      // The stone-wash speckle is fine in the photos: the swatch repeats about seven times around the leg.
      crotch: { top: 1.12, y: .95 }, uvScale: [7, 6.4],
      tiles: { small: [6, 2.8], legs: [1, 1], hips: [1, 1] },
      hips: [[1.31, .264, .168], [1.2, .274, .186], [1.1, .288, .196], [1.02, .296, .198], [.97, .298, .19], [.935, .24, .1]],
      // Relaxed and straight, tapering slightly to an ankle-length hem above the shoes.
      legs: [[1.03, .15, .18, .135], [.95, .155, .178, .15], [.8, .153, .173, .158], [.6, .146, .166, .162], [.42, .141, .159, .162], [.24, .137, .155, .162]],
      hem: 'ankle', folds: { base: .004, low: .008 }, gradient: [.9, .14], whiskers: .1, thighFade: .08,
      waistband: { y: 1.285, rx: .266, rz: .17, h: .05 },
      loops: [-2.6, -1.5, -.62, .62, 1.5, 2.6, Math.PI],
      // The pair's recognisable light grey double topstitching, with paler bleached seams (roping) and a stitched hem.
      button: { colour: '#c9ccd0' }, thread: '#787676', stitchScale: 1.3, doubleSeams: true, roping: 2.6, hemStitch: .014, dartsStitched: true,
      fly: [[.036, 1.26], [.038, 1.13], [.022, 1.085], [0, 1.075]],
      frontPocket: { type: 'scoop', line: [[.15, 1.26], [.165, 1.21], [.2, 1.18], [.262, 1.165]] },
      coinPocket: { outline: [[-.236, 1.255], [-.19, 1.255], [-.194, 1.2], [-.233, 1.2], [-.236, 1.255]] },
      rivets: [[.152, 1.255], [.262, 1.17], [-.19, 1.252]],
      seamEnd: .245,
      // Pockets sit high, as in the back photo, with a short dart running down to each.
      backDarts: [[.11, 1.259], [.115, 1.228]],
      backPocket: { x: .12, outline: [[-.068, 1.222], [.068, 1.222], [.064, 1.11], [0, 1.085], [-.064, 1.11]], stitchBelow: 1.2 },
      centreBack: [[.004, 1.26], [.004, 1.1], [0, 1.0]],
      labelPatch: { name: 'leather-patch', size: [.072, .04, .005], colour: '#1c1b1c', position: [-.08, 1.288, -(.17 + .004)], rotationY: Math.PI + .3 },
    },
  },
  [BERSHKA_GREY_ID]: {
    slot: 'bottom',
    id: BERSHKA_GREY_ID, name: 'Bershka grey wide-leg jeans', family: 'wide-leg-jeans', version: 1,
    status: 'reference-study-awaiting-visual-review', brandAsProvided: 'Bershka',
    source: { note: 'user supplied five phone screenshots of the product gallery: front close-up and full front on model, back on model, waist close-up, front flat lay' },
    referenceViews: ['front on model (close)', 'front on model', 'back on model', 'waist close-up', 'front flat lay'],
    details: ['low to mid rise', 'wide straight legs, full length, resting on the shoes', 'mid grey wash with a fine crinkled texture', 'bleached paler panels down the middle of each thigh and knee, darker sides and hem', 'strong pale whiskers across the hips and upper thighs, front and back', 'silver button and rivets, tonal grey stitching', 'plain back patch pockets'],
    material: { construction: 'rigid denim', composition: 'not visible in the supplied screenshots', finish: 'grey wash with whiskers and fade' },
    fit: { silhouette: 'wide leg', rise: 'low to mid', length: 'full, resting on the shoes', adjustment: 'fixed authored fit for review' },
    uncertainties: ['folds are procedural', 'whisker and fade placement is an interpretation of the photos', 'label lettering not reproduced'],
    authoring: { texture: 'bershka-grey-denim.js: flat-lit seamless swatch processed from the flat lay; fade and whiskers are shaded on the geometry', runtimeGeneration: false, sourcePhotosBundled: 'fabric swatch only' },
    build: {
      template: 'jeans', legName: 'jeans-leg', fallback: [61, 64, 65],
      crotch: { top: 1.18, y: .95 }, uvScale: [5, 2.7],
      tiles: { small: [4, 1.8], legs: [1, 1], hips: [1, 1] },
      hips: [[1.235, .256, .172], [1.14, .276, .193], [1.04, .294, .198], [.97, .306, .19], [.935, .25, .11]],
      legs: [[1.03, .15, .18, .13], [.95, .158, .181, .154], [.75, .166, .184, .168], [.55, .172, .187, .174], [.35, .178, .19, .18], [.18, .183, .193, .185], [.06, .186, .196, .188]],
      hem: 'rests-on-shoe', folds: { base: .005, low: .011, stack: .01 },
      // The wash: darker toward the hem, bleached panels down each thigh and knee, and strong whiskers across the hips.
      gradient: [.6, .5], whiskers: 1.3,
      whiskerLines: { top: 1.16, count: 6, spacing: .034, width: .012, lo: .93, hi: 1.2, back: true },
      centreFade: { strength: 1.5, width: 2.4, peak: .72, reach: .5 },
      waistband: { y: 1.21, rx: .258, rz: .175, h: .05 },
      loops: [-2.7, -1.45, -.55, .55, 1.45, 2.7, Math.PI],
      button: { colour: '#c9ccd0' }, thread: '#8b8986',
      fly: [[.034, 1.183], [.036, 1.09], [.02, 1.05], [0, 1.04]],
      frontPocket: { type: 'scoop', line: [[.15, 1.184], [.165, 1.14], [.2, 1.112], [.262, 1.1]] },
      coinPocket: { outline: [[-.236, 1.18], [-.19, 1.18], [-.194, 1.128], [-.233, 1.128], [-.236, 1.18]] },
      rivets: [[.152, 1.18], [.262, 1.105]],
      seamEnd: .1,
      backYoke: [[.268, 1.182], [.14, 1.162], [.004, 1.142]],
      backPocket: { x: .122, outline: [[-.074, 1.128], [.074, 1.128], [.07, 1.0], [0, .972], [-.07, 1.0]], stitchBelow: 1.07 },
      centreBack: [[.004, 1.142], [.004, 1.05], [0, .985]],
      labelPatch: { name: 'woven-label', size: [.032, .02, .003], colour: '#d8d6d0', position: [-.06, 1.21, -(.175 + .004)], rotationY: Math.PI + .25 },
    },
  },
  [TOMMY_CARPENTER_ID]: {
    slot: 'bottom',
    id: TOMMY_CARPENTER_ID, name: 'Tommy Jeans Remastered carpenter jeans', family: 'carpenter-jeans', version: 1,
    status: 'reference-study-awaiting-visual-review', brandAsProvided: 'Tommy Jeans',
    source: { note: 'user supplied five phone screenshots of an ASOS listing (Tommy Jeans Remastered carpenter jeans in black wash): front on model twice, side close-up, waist close-up, back' },
    referenceViews: ['front on model', 'side close-up', 'front on model (full)', 'front waist close-up', 'back on model'],
    details: ['mid rise', 'relaxed wide straight legs, full length on the model (the user wears them narrower, at the ankle)', 'even black wash', 'white double contrast topstitching throughout', 'large carpenter patch panels over the front hips, from the waistband to the crotch, under the scoop pockets', 'big utility patch pockets on both outer thighs, a red, white and navy flag badge on the wearer\'s left one', 'hammer loop on the wearer\'s right thigh', 'silver button and rivets', 'back yoke, patch pockets, a red, white and navy tape across the wearer\'s right back pocket', 'tonal grey flag patch on the back waistband'],
    material: { construction: 'rigid denim', composition: 'not visible in the supplied screenshots', finish: 'black wash' },
    fit: { silhouette: 'relaxed straight, carpenter', rise: 'mid', length: 'ankle', adjustment: 'narrower and ankle length, as the user wears them (the photos show wide, full-length legs)' },
    uncertainties: ['folds are procedural', 'badges and patches are colour blocks without lettering', 'no coin pocket was visible in the screenshots', 'the fly bar tacks are not modelled'],
    authoring: { texture: 'tommy-carpenter-denim.js: flat-lit seamless swatch processed from the waist close-up, keeping its brightness detail only (the dark photo carries compression colour blotches)', runtimeGeneration: false, sourcePhotosBundled: 'fabric swatch only' },
    build: {
      template: 'jeans', legName: 'jeans-leg', fallback: [11, 10, 14],
      // The swatch comes from a zoomed close-up, so it repeats often to keep the twill at the photo's scale.
      crotch: { top: 1.19, y: .95 }, uvScale: [12, 4.1],
      tiles: { small: [7.5, 2.6], legs: [1, 1], hips: [1, 1] },
      hips: [[1.26, .26, .171], [1.16, .278, .19], [1.05, .294, .198], [.97, .304, .19], [.935, .25, .11]],
      // Relaxed straight legs, narrower than the photos' wide look, ending at her ankle above the shoes (as the user wears them).
      legs: [[1.03, .15, .178, .13], [.95, .154, .176, .152], [.75, .155, .172, .16], [.55, .152, .167, .162], [.38, .148, .162, .163], [.24, .145, .159, .163]],
      hem: 'ankle', folds: { base: .004, low: .009 }, gradient: [.9, .15], whiskers: 0,
      waistband: { y: 1.235, rx: .262, rz: .173, h: .05 },
      loops: [-2.7, -1.45, -.55, .55, 1.45, 2.7, Math.PI],
      button: { colour: '#c9ccd0' }, thread: '#b4b2b8', rivetColour: '#c9ccd0',
      // White double topstitching, as on the Mango pair.
      doubleSeams: true, hemStitch: .022,
      fly: [[.034, 1.208], [.036, 1.115], [.02, 1.075], [0, 1.065]],
      frontPocket: { type: 'scoop', line: [[.13, 1.209], [.15, 1.17], [.195, 1.14], [.262, 1.125]] },
      // Carpenter panels over the front hips, from the waistband to the crotch, stitched along their inner and lower edges.
      frontPanel: { outline: [[.112, 1.21], [.255, 1.21], [.258, 1.06], [.255, .985], [.15, .952]],
        stitch: [[[.118, 1.21], [.137, 1.08], [.155, .958], [.2, .974], [.255, .991]], [[.125, 1.21], [.144, 1.08], [.16, .965], [.2, .981], [.255, .998]]] },
      // Utility pockets on both outer thighs, wrapping from behind the side seam toward the front.
      sidePocket: { top: .9, bottom: .6, span: [-.4, .5], badge: { side: 1, y: .8, t: .22 }, hammerLoop: { side: -1, t: 0, above: .045, below: .02 } },
      rivets: [[.135, 1.205], [.262, 1.13]],
      seamEnd: .245,
      backYoke: [[.268, 1.207], [.14, 1.187], [.004, 1.167]],
      backPocket: { x: .122, outline: [[-.074, 1.153], [.074, 1.153], [.07, 1.025], [0, .997], [-.07, 1.025]], stitchBelow: 1.095,
        // Diagonal tape across the wearer's right pocket: navy, white and red stripes, from its lower outer edge upward.
        tape: { side: -1, line: [[.09, 1.1], [.01, .95]], stripes: [['#1c2747', .013], ['#f2f2f0', .013], ['#c8202f', .013]] } },
      centreBack: [[.004, 1.167], [.004, 1.07], [0, .985]],
      labelPatch: { name: 'flag-patch', size: [.075, .045, .005], colour: '#2b2b30', position: [-.08, 1.238, -(.173 + .004)], rotationY: Math.PI + .3,
        blocks: [[-.034, .0, 0, .02, '#6b6b72'], [0, .0, .034, .02, '#45454c']] },
    },
  },
  // Shoes.
  [BUFFALO_ASPHA_ID]: {
    slot: 'shoes',
    id: BUFFALO_ASPHA_ID, name: 'Buffalo Aspha olive platform boots', family: 'lug-sole-platform-ankle-boot', version: 1,
    status: 'reference-study-awaiting-visual-review', brandAsProvided: 'Buffalo',
    source: { note: 'user supplied five phone screenshots of an Amazon listing ("Buffalo Aspha NC Mid Vegan Nu", colour Verde, size 36 EU): front three-quarter, outer side, back three-quarter, inner side, inner three-quarter' },
    referenceViews: ['front three-quarter', 'outer side', 'back three-quarter', 'inner side', 'inner three-quarter'],
    details: ['chunky tonal platform sole with deep trapezoid lugs, a ledge above the lugs and a raised heel cup', 'toe of the sole lifted (rocker)', 'mid-cut olive vegan nubuck upper, all one colour with the sole', 'padded collar quilted in two horizontal rows', 'tall heel pull tab of jacquard logo tape: grey band reading BUFFALO // between black and taupe woven edges', 'logo tape down the tongue and a tongue pull tab', 'metal eyelets with two taupe webbing lace loops per side', 'flat olive laces', 'curved side overlay edged in dark piping, over a window with two diagonal taupe webbing straps', 'tan double topstitching'],
    material: { construction: 'vegan nubuck upper on a moulded rubber platform', composition: 'not visible in the supplied screenshots', finish: 'matte, softly mottled' },
    fit: { silhouette: 'chunky lug-sole ankle boot', height: 'mid, just above the ankle bone', platform: 'built inside her existing foot height; her body is not raised', adjustment: 'fixed authored fit for review' },
    uncertainties: ['lug count and side-panel curves adapted to her short toy foot', 'the tongue badge, side label and embossed Buffalo script on the heel of the sole carry no lettering', 'tape lettering is redrawn, not copied'],
    authoring: { texture: 'buffalo-tape.js: logo tape drawn locally from the product photos; nubuck and sole colours measured from the photos', runtimeGeneration: false, sourcePhotosBundled: false },
    // Construction for makeLugBoot() in src/doll/model.js, in outfit units (x is widened by 1.06 and y squashed by .76 on screen).
    // Upper rows are [y, front, back, halfWidth]: horizontal slices whose front recedes up the lacing.
    build: {
      template: 'lug-boot', cx: .168,
      colours: { upper: '#514e3f', sole: '#44463e', thread: '#7a6b52', piping: '#2a271f', webbing: '#6e604d', lace: '#47422f', eyelet: '#3b3a37', lining: '#2f2c24' },
      sole: { top: .112, heelTop: .15, heelFrom: -.03, rand: .15, lugTop: .05, groove: .074, flare: .02, toeLift: .03, lugs: 24, lugDepth: .026 },
      // A long, low toe; the lacing climbs diagonally to an ankle shaft. Measured as proportions of the side photos.
      upper: [[.112, .44, -.16, .13], [.13, .445, -.162, .131], [.15, .43, -.165, .13], [.165, .4, -.165, .13], [.18, .355, -.164, .129], [.2, .31, -.162, .13], [.225, .265, -.158, .128], [.25, .228, -.155, .127], [.28, .198, -.15, .126], [.31, .175, -.145, .126], [.335, .155, -.138, .124], [.36, .14, -.132, .108], [.385, .132, -.13, .104]],
      collar: { front: .365, side: .345, back: .385 },
      nFront: 2.3, nBack: 2, heelNarrow: .12, toeNarrow: .22, restCap: .22, collarRoll: .017, quilt: [.035, .07],
      eyelets: [.195, .215, .235, .33, .35], loops: [.265, .297], laceHalfWidth: .044,
      heelTab: { width: .056, from: .18, above: .08 }, tongueTab: { width: .046, above: .045 },
      // Side overlay, window, straps and vamp seam as [z, y] paths along each side.
      sides: {
        arch: [[-.115, .165], [-.01, .2], [.09, .243], [.15, .27], [.19, .29]],
        window: [[0, .15], [.02, .18], [.12, .186], [.2, .15], [.225, .122]],
        straps: [[[.025, .128], [.07, .178]], [[.105, .125], [.15, .176]]],
        vamp: [[.265, .2], [.285, .16], [.3, .122]],
      },
    },
  },
});
