// Authored wardrobe entries. These describe assets, not runtime AI requests.
export const BRONZE_TOP_ID = 'desigual-bronze-mesh-v1';
export const LILAC_TOP_ID = 'lilac-portrait-mockneck-v1';
export const CROCHET_TOP_ID = 'desigual-crochet-flowers-v1';
export const PLAID_JUMPER_ID = 'mango-plaid-jumper-v1';
export const BARREL_JEANS_ID = 'topshop-barrel-jeans-v1';
export const GARMENTS = Object.freeze({
  [BRONZE_TOP_ID]: {
    slot: 'top',
    id: BRONZE_TOP_ID,
    name: 'Bronze Buddha mesh',
    family: 'fitted-long-sleeve-top',
    version: 1,
    status: 'user-liked-after-elbow-correction',
    brandAsProvided: 'Desigual',
    referenceViews: ['front', 'back'],
    details: ['bronze glitter and opaque black horizontal stripes', 'front-facing Buddha on both torso panels', 'neon green outlined sleeve graphics', 'soft white airbrushed patches', 'black bound crew neck', 'long fitted sleeves'],
    material: { construction: 'fine stretch mesh', finish: 'metallic flecks', opaqueBands: 'black' },
    fit: { silhouette: 'close to doll body', sleeve: 'tapered', hem: 'hip', adjustment: 'fixed authored fit for first review' },
    exclusions: ['striped-shirt', 'knit-sweater'],
    layering: { coversWaistband: true },
    uncertainties: ['exact sleeve characters are not transcribed', 'generated artwork is interpretive', 'same front-facing motif is reused on back', 'side seam alignment and physical transparency need visual review'],
    authoring: { texture: 'bronze-atlas.js', runtimeGeneration: false, sourcePhotosBundled: false },
  },
  [LILAC_TOP_ID]: {
    slot: 'top',
    id: LILAC_TOP_ID, name: 'Lilac portrait mock neck', family: 'fitted-long-sleeve-top', version: 1,
    status: 'reference-study-awaiting-visual-review', brandAsProvided: null,
    referenceViews: ['front','back'],
    details: ['mauve portrait and flowers on front', 'plain pale silvery-lilac back', 'navy sleeves with alternating circle and dot bands', 'short raised ribbed neck', 'long sleeves with wrist gathering', 'longer close-fitting torso'],
    material: { construction: 'textured fabric; exact fibre unconfirmed', finish: 'subtle metallic back sheen' },
    fit: { silhouette: 'close to doll body', sleeve: 'tapered with cuff gathers', hem: 'lower hip', adjustment: 'fixed authored fit for review' },
    exclusions: ['striped-shirt','knit-sweater'],
    layering: { coversWaistband: true },
    uncertainties: ['portrait and floral artwork are interpretive', 'physical material and brand are not established from pictures', 'exact seam placement and print scale need visual review'],
    authoring: { texture: 'lilac-atlas.js', runtimeGeneration: false, sourcePhotosBundled: false },
  },
  [CROCHET_TOP_ID]: {
    slot: 'top',
    id: CROCHET_TOP_ID, name: 'Blue crochet flowers', family: 'cropped-crochet-sweater', version: 1,
    status: 'reference-study-awaiting-visual-review', brandAsProvided: 'Desigual',
    source: { page: 'https://www.desigual.com/it_IT/26SWJFXG.html', sku: '26SWJFXG5050', fetchedForAuthoring: '2026-10-08' },
    referenceViews: ['front on model', 'back three-quarter on model', 'front flat lay', 'street action'],
    details: ['joined hexagonal flower motifs: navy petals with spoked turquoise centres, pale-blue petals, cream petals with navy centres, small navy wheels', 'open cream lace between motifs', 'wide filet-crochet neckband on a broad scoop neck', 'cropped boxy body', 'long slightly flared sleeves reaching the knuckles', 'scalloped hem and cuffs'],
    material: { construction: 'joined crochet motifs with openwork filler', composition: '60% cotton, 40% acrylic per composition section; the same page also says 100% cotton', finish: 'matte yarn' },
    fit: { silhouette: 'boxy, cropped at the waist', sleeve: 'slightly flared, covers half the mitten', hem: 'scalloped at waist', adjustment: 'fixed authored fit for review' },
    exclusions: ['striped-shirt','knit-sweater'],
    uncertainties: ['motif layout is a procedural repeat, not a stitch-for-stitch copy', 'upper back and back neckline are hidden by hair in the back photo', 'dropped shoulders and the ladder seams at shoulder and sleeve are not modelled', 'scallops do not follow individual motif edges'],
    authoring: { texture: 'procedural crochetData() in src/doll/model.js, drawn locally when first worn', runtimeGeneration: false, sourcePhotosBundled: false },
  },
  [PLAID_JUMPER_ID]: {
    slot: 'top',
    id: PLAID_JUMPER_ID, name: 'Brushed windowpane jumper', family: 'oversized-knit-jumper', version: 1,
    status: 'reference-study-awaiting-visual-review', brandAsProvided: 'Mango',
    source: { page: 'https://www.zalando.ie/mango-jumper-light-blue-zir03dt4f-001.html', note: 'page blocked automated fetching; user supplied phone screenshots of 7 product photos' },
    referenceViews: ['front on model', 'front full length', 'knit close-up', 'back on model', 'sleeve and hem close-up', 'front flat lay', 'crouching side'],
    details: ['large windowpane check knitted in (jacquard), not printed', 'wide bands of diagonal hatching in rust-brown and grey-taupe', 'thin pale-blue lines through bands and cream windows', 'brushed fuzzy cream ground', 'ribbed crew neck', 'deep ribbed hem band', 'ribbed cuffs gathering full sleeves', 'oversized boxy body with dropped shoulders'],
    material: { construction: 'heavy brushed jacquard knit', composition: 'not visible in the supplied screenshots', finish: 'soft halo' },
    fit: { silhouette: 'oversized, boxy', sleeve: 'full, gathered into ribbed cuffs', hem: 'hip, deep rib band', adjustment: 'fixed authored fit for review' },
    wear: { userNote: 'rarely worn: oversized and very warm for the local climate' },
    exclusions: ['striped-shirt','knit-sweater'],
    layering: { coversWaistband: true },
    uncertainties: ['check scale and band order are an interpretation of the photos', 'fibre composition is unknown', 'the shirt collar and cuffs in the photos are styling, not part of the jumper'],
    authoring: { texture: 'procedural plaidData() in src/doll/model.js, drawn locally when first worn', runtimeGeneration: false, sourcePhotosBundled: false },
  },
  [BARREL_JEANS_ID]: {
    slot: 'bottom',
    id: BARREL_JEANS_ID, name: 'Acid-wash barrel jeans', family: 'barrel-leg-jeans', version: 1,
    status: 'user-approved-after-revisions', brandAsProvided: 'Topshop',
    source: { note: 'user supplied four phone screenshots of the product gallery (front on model, back detail, back full length, flat lay)' },
    referenceViews: ['front on model', 'back pocket close-up', 'back full length', 'front flat lay'],
    details: ['low rise', 'very wide barrel (horseshoe) legs, widest around the knee, full length resting on the shoes', 'side seams twisting forward toward the hem', 'horizontal darts across each knee', 'slanted front pockets', 'belt loops, silver shank button and zip fly', 'tan contrast topstitching', 'back yoke and patch pockets with pointed buttoned flaps', 'welt slit above the right back pocket', 'brown suede waistband patch', 'mid-dark blue marbled acid wash with a grey cast'],
    material: { construction: 'rigid denim', composition: 'not visible in the supplied screenshots', finish: 'marbled acid wash' },
    fit: { silhouette: 'barrel', rise: 'low', length: 'full, resting on the shoes', adjustment: 'fixed authored fit for review' },
    uncertainties: ['folds are procedural', 'exact pocket and dart placement adapted to the doll', 'brand text on the patch is not reproduced'],
    authoring: { texture: 'topshop-denim.js: flat-lit seamless swatch processed from the product flat lay (at the user\'s request)', runtimeGeneration: false, sourcePhotosBundled: 'fabric swatch only' },
    // Construction for makeJeans() in src/doll/model.js. Rows are [y, rx, rz] (hips) and [y, rx, rz, cx] (legs).
    build: {
      template: 'jeans', legName: 'barrel-leg',
      tiles: { small: [2.45, .66], legs: [4, 1], hips: [6, .26] },
      hips: [[1.22, .255, .172], [1.13, .276, .193], [1.04, .292, .198], [.97, .3, .186], [.935, .25, .11]],
      legs: [[1.03, .145, .185, .13], [.95, .158, .185, .158], [.75, .168, .188, .172], [.55, .172, .188, .176], [.35, .17, .186, .174], [.18, .167, .184, .17], [.06, .166, .183, .168]],
      hem: 'rests-on-shoe', folds: { base: .005, low: .011, stack: .011 }, twist: Math.PI / 4, kneeSeams: .64,
      gradient: [.86, .22], whiskers: .12,
      waistband: { y: 1.195, rx: .258, rz: .175, h: .05 },
      loops: [-2.7, -1.45, -.55, .55, 1.45, 2.7, Math.PI],
      button: { colour: '#c9ccd0' }, thread: '#8f744f',
      fly: [[.034, 1.168], [.036, 1.08], [.02, 1.045], [0, 1.035]],
      frontPocket: { type: 'slant', line: [[.165, 1.168], [.218, 1.11], [.265, 1.065]] },
      sideSeamTop: [[.278, 1.12], [.29, 1.04]], seamEnd: .1,
      backYoke: [[.272, 1.165], [.14, 1.148], [.004, 1.13]],
      backPocket: { x: .122, outline: [[-.076, 1.11], [.076, 1.11], [.073, .99], [0, .958], [-.073, .99]], stitchBelow: 1.05,
        flap: [[-.082, 1.128], [.082, 1.128], [.08, 1.084], [0, 1.062], [-.08, 1.084]],
        flapStitch: [[-.074, 1.12], [.074, 1.12], [.072, 1.088], [0, 1.07], [-.072, 1.088], [-.074, 1.12]], button: 1.076 },
      centreBack: [[.004, 1.13], [.004, 1.05], [0, .99]],
      welt: [[-.19, 1.14], [-.07, 1.137]],
      labelPatch: { name: 'suede-patch', size: [.088, .05, .005], colour: '#a87348', position: [.07, 1.2, -(.177 + .004)], rotationY: Math.PI - .27 },
    },
  },
});
